package:
  name: denet
  version: ${{ env.get("PKG_VERSION") | default("0.6.2") }}

source:
  path: ../..

build:
  number: 0
  script:
    - if: unix
      then: bash ${RECIPE_DIR}/build.sh
    - if: win
      then: cmd /C %RECIPE_DIR%\build.cmd

requirements:
  build:
    - ${{ compiler('rust') }}
    - if: linux
      then: pkg-config

tests:
  - if: not win
    then:
      script:
        interpreter: bash
        content: |
          denet --version
  - if: win
    then:
      script:
        interpreter: cmd
        content: denet --version
